import rectangle1 from "../../images/Rectangle1.png"
import rectangle2 from "../../images/Rectangle2.png"
import rectangle3 from "../../images/Rectangle3.png"
import rectangle4 from "../../images/Rectangle4.png"
import rectangle5 from "../../images/Rectangle5.png"
import rectangle6 from "../../images/Rectangle6.png"
import location from "../../logos/location.png"
import bed from "../../logos/bed.png"
import bath from "../../logos/bath.png"
import img1 from "../../images/img1.png"
import img2 from "../../images/img2.png"
import img3 from "../../images/img3.png"
import img4 from "../../images/img4.png"


const ApartmentData=[
    {
        id:1,
        img: rectangle1,
        img1:img1,
        img2:img2,
        img3:img3,
        img4:img4,
        picture:location,
        photo:bath,
        cobi:bed,
        houseName:'Washington Avenue',
      location:'Nasirabad H/S Chattogram',
      bedroom:'2 Bedrooms',
      Bathroom:'2 Bathroom',
      price:'$244',
      summery:'300 sq-ft, 3 Bedroom, Semi-furnished, Luxurious,South facing Apartment for Rent in Rangs Malancha,Melbourne',
      rent:'Rent/Month:$550(negotiable)',
      serviceCharge:'8000/=Tk per month,subject to change',
      securityDeposit:'3 months earlier notice required ',
      flat:'3 months earliar notice required',
      address:'Ranges Malancha,House-68,Road-6A(Dead end Road),Dhanmondi Residential Area',
      flatSize:'3000 Sq Feet',
      floor:'A5 (5th Floor)(6 storied Building)(South Facing Unit)',
      roomCatagori:'3 Large Bed Rooms with 3 Varandas,spacious Drawing,Dining & Family Living Rooms,Highly Decorated Kitchen with store Rooms and servant rooms with attached Toilet.',
      facilities:'1 Modern Lift, All Modern Amenities & Semi Furnished ',
      additional:'a.Electricity with fullgenerator load, b.Central Gas Geyser, c.2 Car Parking with 1 Drivers Accommodation, d. community conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f.Cloth Hanbging facility with CC camera  ',
    },
    { 
        id:2,
        img:rectangle2,
        img1:img1,
        img2:img2,
        img3:img3,
        img4:img4,
        picture:location,
        photo:bath,
        cobi:bed,
        houseName:'Familly Appartment',
        location:'Nasirabad H/S Chattogram',
        bedroom:'2 Bedrooms',
        Bathroom:'2 Bathroom',
        price:'$321',
         summery:'400 sq-ft, 4 Bedroom, Semi-furnished, Luxurious,South facing Apartment for Rent in Rangs Australia,Melbourne',
         rent:'Rent/Month:$450(negotiable)',
         serviceCharge:'7000/=Tk per month,subject to change',
         securityDeposit:'2 months rent',
         flat:'2 months earliar notice required',
         address:'Ranges Australia,House-68,Road-6A(Dead end Road),Melborn Residential Area',
         flatSize:'3500 Sq Feet',
         floor:'A5 (5th Floor)(5 storied Building)(South Facing Unit)',
         roomCatagori:'4 Large Bed Rooms with 4 Varandas,spacious Drawing,Dining & Family Living Rooms,Highly Decorated Kitchen with store Rooms and servant rooms with attached Toilet.',
         facilities:'1 Modern Lift, All Modern Amenities & Semi Furnished ',
         additional:'a.Electricity with fullgenerator load, b.Central Gas Geyser, c.2 Car Parking with 1 Drivers Accommodation, d. community conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f.Cloth Hanbging facility with CC camera  ',
    },
    {
        id:3,
        img:rectangle3,
        img1:img1,
        img2:img2,
        img3:img3,
        img4:img4,
        picture:location,
        photo:bath,
        cobi:bed,
        houseName:'Gorgeous House',
        location:'Nasirabad H/S Chattogram',
        bedroom:'2 Bedrooms',
        Bathroom:'2 Bathroom',
        price:'$345',
        summery:'500 sq-ft, 8 Bedroom, Semi-furnished, Luxurious,South facing Apartment for Rent in Rangs Indea,Mombai',
        rent:'Rent/Month:$550(negotiable)',
        serviceCharge:'6000/=Tk per month,subject to change',
        securityDeposit:'4 months rent',
        flat:'4 months earliar notice required',
        address:'Ranges India,House-58,Road-6A(Dead end Road),India Mombai Area',
        flatSize:'4000 Sq Feet',
        floor:'A5 (5th Floor)(8 storied Building)(South Facing Unit)',
        roomCatagori:'6 Large Bed Rooms with 5 Varandas,spacious Drawing,Dining & Family Living Rooms,Highly Decorated Kitchen with store Rooms and servant rooms with attached Toilet.',
        facilities:'2 Modern Lift, All Modern Amenities & Semi Furnished ',
        additional:'a.Electricity with fullgenerator load, b.Central Gas Geyser, c.2 Car Parking with 1 Drivers Accommodation, d. community conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f.Cloth Hanbging facility with CC camera  ',
    },
    { 
        id:4,
        img:rectangle4,
        img1:img1,
        img2:img2,
        img3:img3,
        img4:img4,
        picture:location,
        photo:bath,
        cobi:bed,
        houseName:'Luxary Villa',
        location:'Nasirabad H/S Chattogram',
        bedroom:'2 Bedrooms',
        Bathroom:'2 Bathroom',
        price:'$999',
        summery:'200 sq-ft, 5 Bedroom, Semi-furnished, Luxurious,South facing Apartment for Rent in Rangs Canda, ottwa',
        rent:'Rent/Month:$350(negotiable)',
        serviceCharge:'4200/=Tk per month,subject to change',
        securityDeposit:'4 months rent',
        flat:'3 months earliar notice required',
        address:'Range Canda,House-88,Road-6A(Dead end Road),Canada ottwa Area',
        flatSize:'3500 Sq Feet',
        floor:'A5 (7th Floor)(10 storied Building)(South Facing Unit)',
        roomCatagori:'6 Large Bed Rooms with 4 Varandas,spacious Drawing,Dining & Family Living Rooms,Highly Decorated Kitchen with store Rooms and servant rooms with attached Toilet.',
        facilities:'2 Modern Lift, All Modern Amenities & Semi Furnished ',
        additional:'a.Electricity with fullgenerator load, b.Central Gas Geyser, c.2 Car Parking with 1 Drivers Accommodation, d. community conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f.Cloth Hanbging facility with CC camera  ',

    },
    {
        id:5,
        img:rectangle5,
        img1:img1,
        img2:img2,
        img3:img3,
        img4:img4,
        picture:location,
        photo:bath,
        cobi:bed,
        houseName:'Epic Huda Falacio',
        location:'Nasirabad H/S Chattogram',
        bedroom:'2 Bedrooms',
        Bathroom:'2 Bathroom',
        price:"$458",
        summery:'850 sq-ft, 7 Bedroom, Semi-furnished, Luxurious,South facing Apartment for Rent in Rangs Pakistan,koraci',
        rent:'Rent/Month:$450(negotiable)',
        serviceCharge:'6500/=Tk per month,subject to change',
        securityDeposit:'5 months rent',
        flat:'4 months earliar notice required',
        address:'Ranges Pakistan,House-55,Road-6A(Dead end Road),Pakistan Koraci Area',
        flatSize:'3500 Sq Feet',
        floor:'A5 (7th Floor)(12 storied Building)(South Facing Unit)',
        roomCatagori:'8 Large Bed Rooms with 4 Varandas,spacious Drawing,Dining & Family Living Rooms,Highly Decorated Kitchen with store Rooms and servant rooms with attached Toilet.',
        facilities:'2 Modern Lift, All Modern Amenities & Semi Furnished ',
        additional:'a.Electricity with fullgenerator load, b.Central Gas Geyser, c.2 Car Parking with 1 Drivers Accommodation, d. community conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f.Cloth Hanbging facility with CC camera  ',
    },
    { 
        id:6,
        img:rectangle6,
        img1:img1,
        img2:img2,
        img3:img3,
        img4:img4,
        picture:location,
        photo:bath,
        cobi:bed,
        houseName:'Washington Avenue',
        location:'Nasirabad H/S Chattogram',
        bedroom:'2 Bedrooms',
        Bathroom:'2 Bathroom',
        price:'$550',
        summery:'750 sq-ft, 4 Bedroom, Semi-furnished, Luxurious,South facing Apartment for Rent in Rangs England,Lndon',
        rent:'Rent/Month:$860(negotiable)',
        serviceCharge:'10000/=Tk per month,subject to change',
        securityDeposit:'8 months rent',
        flat:'8 months earliar notice required',
        address:'Ranges England,House-28,Road-6A(Dead end Road),London Residential Area',
        flatSize:'6599 Sq Feet',
        floor:'A3 (10th Floor)(20 storied Building)(South Facing Unit)',
        roomCatagori:'10 Large Bed Rooms with 4 Varandas,spacious Drawing,Dining & Family Living Rooms,Highly Decorated Kitchen with store Rooms and servant rooms with attached Toilet.',
        facilities:'5 Modern Lift, All Modern Amenities & Semi Furnished ',
        additional:'a.Electricity with fullgenerator load, b.Central Gas Geyser, c.2 Car Parking with 1 Drivers Accommodation, d. community conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f.Cloth Hanbging facility with CC camera  ',
    },
]
export default ApartmentData;